# Generated by Django 6.0 on 2025-12-29 21:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignepanier',
            name='quantite',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('mode_paiement', models.CharField(choices=[('cash', 'Paiement à la livraison'), ('orange_money', 'Orange Money'), ('moov_money', 'Moov Money'), ('carte', 'Carte bancaire')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('initie', 'Initié'), ('en_cours', 'En cours'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('annule', 'Annulé'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('numero_telephone', models.CharField(blank=True, help_text='Numéro de téléphone pour Mobile Money', max_length=20)),
                ('code_transaction', models.CharField(editable=False, help_text='Code unique de transaction', max_length=50, unique=True)),
                ('reference_externe', models.CharField(blank=True, help_text='Référence du fournisseur de paiement', max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_initiation', models.DateTimeField(blank=True, null=True)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('message_erreur', models.TextField(blank=True, help_text="Message d'erreur si le paiement échoue")),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données supplémentaires de la transaction')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='Shop.commande')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='TransactionMobileMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(choices=[('orange_money', 'Orange Money'), ('moov_money', 'Moov Money')], max_length=20)),
                ('numero_emetteur', models.CharField(max_length=20)),
                ('numero_recepteur', models.CharField(max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frais', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('id_transaction_operateur', models.CharField(max_length=100, unique=True)),
                ('statut_operateur', models.CharField(max_length=50)),
                ('message_operateur', models.TextField(blank=True)),
                ('date_tentative', models.DateTimeField(auto_now_add=True)),
                ('date_callback', models.DateTimeField(blank=True, null=True)),
                ('requete_json', models.JSONField(default=dict, help_text="Requête envoyée à l'opérateur")),
                ('reponse_json', models.JSONField(default=dict, help_text="Réponse reçue de l'opérateur")),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Shop.paiement')),
            ],
            options={
                'verbose_name': 'Transaction Mobile Money',
                'verbose_name_plural': 'Transactions Mobile Money',
                'ordering': ['-date_tentative'],
            },
        ),
    ]
