# Generated by Django 6.0 on 2026-01-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_alter_lignepanier_quantite_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='par_commande',
            field=models.BooleanField(default=False, help_text='Indique si le produit doit se daire par commande'),
        ),
    ]
